import React from 'react';
import { Download } from 'lucide-react';
import { useData } from '../context/DataContext';
import { saveAs } from 'file-saver';

const ExportReport: React.FC = () => {
  const { filteredSurgeries, filters, hasData } = useData();

  const generateReport = () => {
    if (!hasData || filteredSurgeries.length === 0) {
      alert('No data available to export.');
      return;
    }

    const currentDate = new Date();
    const dateStr = currentDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit'
    });
    const timeStr = currentDate.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true
    });

    const totalCases = filteredSurgeries.length;
    const averageDuration = totalCases > 0 
      ? Math.round(filteredSurgeries.reduce((sum, surgery) => sum + surgery.duration, 0) / totalCases)
      : 0;

    const lastCase = [...filteredSurgeries].sort((a, b) => 
      b.datetime.getTime() - a.datetime.getTime()
    )[0];

    const uniqueSurgeons = new Set(filteredSurgeries.map(s => s.surgeon_name)).size;
    const uniqueProcedures = new Set(filteredSurgeries.map(s => s.procedure_name)).size;
    const uniqueInstruments = new Set(
      filteredSurgeries.flatMap(surgery => 
        surgery.instruments.map(instrument => instrument.name)
      )
    ).size;
    const totalConsoleTime = filteredSurgeries.reduce((sum, surgery) => sum + surgery.duration, 0);

    const instrumentStats = filteredSurgeries.reduce((acc, surgery) => {
      surgery.instruments.forEach(instrument => {
        if (!acc[instrument.name]) {
          acc[instrument.name] = { totalDuration: 0, count: 0 };
        }
        acc[instrument.name].totalDuration += instrument.duration;
        acc[instrument.name].count += 1;
      });
      return acc;
    }, {} as Record<string, { totalDuration: number; count: number }>);

    const instrumentUsage = Object.entries(instrumentStats).map(([name, stats]) => {
      const avgDuration = Math.round(stats.totalDuration / stats.count);
      const percentage = totalConsoleTime > 0 ? Math.round((stats.totalDuration / totalConsoleTime) * 100) : 0;
      return { name, avgDuration, percentage };
    });

    const reportContent = `MISSO SYSTEM INSIGHTS
Surgery Report

Date & Time: ${dateStr}, ${timeStr}
Procedure Name: ${filters.procedure || 'All Procedures'}
Surgeon: ${filters.surgeon || 'All Surgeons'}
Total Cases: ${totalCases}
Average Case Duration: ${averageDuration} minutes

Last Case Summary
Duration: ${lastCase ? lastCase.duration : 'N/A'} minutes
Surgeon: ${lastCase ? lastCase.surgeon_name : 'N/A'}

Quick Statistics
Total Procedures Conducted: ${totalCases}
Average Duration: ${averageDuration} minutes
Unique Surgeons: ${uniqueSurgeons}
Procedure Types: ${uniqueProcedures}
Unique Instruments: ${uniqueInstruments}
Total Console Time: ${totalConsoleTime} minutes

Instruments Usage
${instrumentUsage.length > 0 ? instrumentUsage.map(inst => 
  `${inst.name}: ${inst.avgDuration} minutes (${inst.percentage}%)`
).join('\n') : 'No instruments used'}

Generated by MISSO System Insights Dashboard`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const fileName = `MISSO_Surgery_Report_${dateStr.replace(/\//g, '-')}.txt`;
    saveAs(blob, fileName);

    const notification = document.createElement('div');
    notification.textContent = 'Report exported successfully!';
    notification.className = 'fixed top-20 right-4 bg-[#00938e] text-white px-4 py-2 rounded-lg shadow-lg z-50';
    document.body.appendChild(notification);
    setTimeout(() => {
      document.body.removeChild(notification);
    }, 3000);
  };

  return (
    <button
      onClick={generateReport}
      disabled={!hasData || filteredSurgeries.length === 0}
      className={`w-full flex items-center justify-center gap-2 p-3 border-2 border-[#00938e] rounded-lg transition-colors ${
        hasData && filteredSurgeries.length > 0
          ? 'bg-white hover:bg-[#00938e] hover:text-white'
          : 'bg-gray-300 text-gray-500 cursor-not-allowed'
      }`}
    >
      <Download size={20} />
      <span className="text-sm font-medium">Export Report</span>
    </button>
  );
};

export default ExportReport;